### ISSUE TITLE
Can I specify a vim instance name where file would be opened?

### ISSUE THREAD

**Issue by justrajdeep** [susam/vimer#1]
Hi 

Is it possible to update the script to take the vim instance name as an argument where the file would be opened.

If that can be supported that would be super awesome.

Thanks in advance

**Comment by susam** [comment]
Thanks for opening this issue and describing the feature you wanted.

This has been resolved now in commit 486e2b71910c137f24abda027e8c63d6ad784a9b and available in version 0.2.0.

A new option, `-s` or `--server`, has been added to open a new GVim or MacVim instance with a specified server name or open files in an existing instance with a specified server name.

**Comment by justrajdeep** [comment]
thanks a lot
