### ISSUE TITLE
Why use `findstr` to create an empty file on Windows?

### ISSUE THREAD

**Issue by b-** [susam/vimer#3]
I was perusing the code here after seeing this on lobste.rs, and I was very confused by the following line, https://github.com/susam/vimer/blob/23a5246a2e26316e2e9d02e04ee437e29c4f7ca7/vimer.cmd#L185

I don’t have a Windows computer handy to see if there’s anything going on that I’m missing, but based on the comment it sounds like this just creates an empty file, a la `touch` on *nix. If this indeed is what’s going on, `copy nul > file` is a more supported (and potentially faster) way to do just that.

**Comment by susam** [comment]
The command `findstr "^" > "%stdin_file%"` mimics the behaviour of `cat > "$stdin_file"` on Unix. Compare https://github.com/susam/vimer/blob/23a5246a2e26316e2e9d02e04ee437e29c4f7ca7/vimer.cmd#L185 with https://github.com/susam/vimer/blob/23a5246a2e26316e2e9d02e04ee437e29c4f7ca7/vimer#L170 to see the similarity.

Here is an example on Windows:

```
C:\>echo hello | findstr "^"
hello

C:\>echo hello | findstr "^" > out.txt

C:\>type out.txt
hello
```

Here is a similar example on Unix:

```
$ echo hello | cat
hello
$ echo hello | cat > out.txt             
$ cat out.txt
hello
```
